name: haskell-template-task-embedded
ghc-options:
  -Wall
dependencies:
  - base
  - deepseq
  - haskell-src-exts
  - HUnit
  - IOTasks
  - QuickCheck
  - random
  - syb
library:
  source-dirs: src
  other-modules:
    - TestHarness
    - TestHelper
