---
name: Haskell Linter

on:
  push:
    branches: ["master", "workflows"]
  pull_request:
    branches: ["master"]

permissions: read-all

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Set up HLint'
        uses: haskell-actions/hlint-setup@v2
        with:
          version: '3.8'

      - name: 'Run HLint'
        uses: haskell-actions/hlint-run@v2
        with:
          path: '["src/", "raw/src/", "raw/embedded/src/"]'
          fail-on: suggestion
